# Appendix: Backlog {#backlog}

- Make sure you are using AICc, not AIC

- Accommodate species belonging to multiple cohorts in GoogleSheet framework  

- Remove `random.seed` from settings functions.  

- Investigate discrepancies between output from `format_distance()` and `summarize_effort()`.  

- Follow-through on converting `format_distance()` to match the formatting from `ABUND9`? (It is currently matching the format from `ABUND7`).  

- Fix polygon area estimation! (Currently does not subtract land area! Ack!)  

- Should LTabundR accept Bft values of NA? Or include an option for interpolating replacement values based on the preceding and proceding values? Or just leave it to analysts to correct the DAS data?

- Consider making the minimum group size for group size calibration (for unknown observers) a cohort-specific setting that users can define.  Update all package and vignette documentation accordingly. 

- Consider making the km gap handling arguments for `format_das()` (and its subroutine `process_km()`) into survey settings that users can define. Update all package and vignette documentation accordingly. 

- Add options to `das_load()` that allows you to determine timezone from date and lat/long, then adjust DateTime accordingly. This would avoid errors in the manual specification of GMT offset within the DAS data. 

- Jay uses the phrase 'stratify by IO': add segmentizing feature in which segment is reset if IO status changes. 

- Main Islands map bbox  

- Map bbox for SoCal, Central Cal, and northern CCS  

- Figure out which ETP strata to have as defaults for both survey strata and study area polygons (there are like 100 in the folder Jeff sent us).  May be a question for Tim G.  

- Test this code on lots of cruise data files to establish basic functionality for Hawaii, California Current, and ETP.   

- Troubleshoot why longitudes are not displayed on Hawaii base map

- Accommodate subgroup settings for FKW analyses

- Method for stratifying by Beaufort.  

- `study_area_explore()` and `study_area_select()`.  

- LTabundR is finding more effort in Cruise 1642 than is ABUND. See the slides detailing the ABUND v LTabundR comparison.  

- `swfscDAS` can accidentally exclude sightings when the GMTOffset field is incorrect; this can be addressed by (i) correcting the DAS file so that GMToffset is correct, (ii) modifying the swfscDAS code, or (iii) building a function for LTabundR that tests and corrects the GMToffset field based upon lat/long and the date. This currently affects only two sightings in Cruise 1004.  

- When observer positions are not entered correctly, sightings will be excluded from analysis. For example, when a sighting is manually entered without correctly establishing observer positions in a previous DAS line, the swfscDAS functions will put NA’s in the ObsL and ObsR data fields. This currently affects only one sighting in Cruise 1607. This can be addressed by (i) leaving as is, (ii) assuming invalid ObsL and ObsR are allowed to be included, or (iii) developing a LTabundR feature in which NA values are replaced based on preceding/subsequent values.  

- When the Bft value is missing, LTabundR does not include the sighting in analysis. This can be addressed by (i) leaving as is (if the DAS data are incorrect, LTabundR will not fix it); (ii) assuming all Bft == NA are valid; or by (iii) developing a LTabundR feature in which NA values are replaced based on preceding/subsequent values. This currently affects two sightings (one in cruise 1607, one in cruise 1621).  

- When sightings occur exactly upon the boundary of a geostratum, LTabundR considers it ‘out’ and excludes it from analysis. ABUND, in contrast, considers it in. This affects one sighting in cruise 1080. We have put an item in the backlog to consider changing this feature.  

- ABUND has some TotSS estimates that are less than 1 (n= about 50). Most of these sightings have ‘raw’ SS estimates of 1 and at least 1 observer(s) who *is* in the SS calibration DAT file, which means their calibration must have produced an estimate less than 1. It makes sense to me that LTabundR should implement a minimum SS of 1 for each observer’s estimate, which should be applied *after* calibration.   

- In the ABUND SSCAL routine, when an observer’s coefficients are drawn from the DAT file, the first line of best-high-low weights is used regardless of whether the general model or the year-specific model is used. Is that how it should be? For a few observers (only a few), the second row of weights differs from the first row.  

- The ABUND SSCAL routine assumes Bft == 0 if it is NA. Are we OK with assuming that, or should we bypass calibration in the event of a missing Bft value? There is just 1 sighting with Bft == NA (Cruise 1607, 1997-04-27 07:16:01, SightNo 68, SpCode 037 killer whale).  







